name: Code Hygiene

on: [push, pull_request]

jobs:
  spotless:
    runs-on: ubuntu-latest
    name: Spotless scan
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true
          arguments: spotlessCheck

  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle scan
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true
          arguments: checkstyleMain checkstyleTest
